// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/danmakufactory.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class DanmakufactoryBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DanmakufactoryBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DanmakufactoryBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();

  ffi.Pointer<ffi.Char> testHi() {
    return _testHi();
  }

  late final _testHiPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('testHi');
  late final _testHi = _testHiPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  int runCmd(ffi.Pointer<ffi.Char> cmd) {
    return _runCmd(cmd);
  }

  late final _runCmdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'runCmd',
      );
  late final _runCmd = _runCmdPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();
}
